#! /bin/sh
# =============
# Commands to be run at startup 

(wal -R && sleep 1s) &
(picom -b && sleep 1s) & 
(~/.local/bin/launchpolybar && sleep 1s) &
(wmname LG3D && sleep 1s) &
(/usr/libexec/polkit-gnome-authentication-agent-1 && sleep 1s) &
