#! /bin/sh

# Some startup commands
sxhkd &
~/.config/bspwm/autostart
xsetroot -cursor_name left_ptr &

# desktop definitions
bspc monitor -d I II III IV V VI VII VIII IX X

# border colors
bspc config active_border_color #131212

# window border width and gap
bspc config border_width         2
bspc config window_gap          12

# split ratio
bspc config split_ratio          0.52

# monocle windows
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# application rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' 
bspc rule -a mplayer2 state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Xephyr state=fullscreen
